apiVersion: v1
kind: Secret
metadata:
    name: certificates
    namespace: simple
stringData:
    server.crt: ENC[AES256_GCM,data:CE24oLz9PQ==,iv:hvUdYRAdGPb1wBeb+j3TGIf8F8Cw8pbD+D2aWIwTIF4=,tag:0HZLK+45Gx5/ldvh6mx8cQ==,type:str]
    server.key: ENC[AES256_GCM,data:XMCltAPR939f1WgKCeAECaxPngW5NHEMTo33/OASaoGuc5otWwhgzoIAXCNtIg01MSe2pWdctfhcFdthpPYlPDrj2fvTB/1ko5kkyG0iaYlFt1QfQeD+M66LdCtq7w==,iv:SBGWvQ2npCEjzirs0IC/jeSYzFrUTqCcxisBuAWGH7k=,tag:fmr+xjERO60M7JHNX7+8yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17putd49qeggegt8nlwvtruq8fut5lsny3894e0vta9mpn6udvpvs8809zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d3JJeXozRVN2R3lYTG1K
            QWt0N3JENlpTcUt1R2xSd1FPRisyTk11VEZvClNORWNQczhvOVo2dnZ1TU1ib1FN
            MFZQeUM4aG5wQmVnamQ0cmR6T05EQm8KLS0tIDNyYkhVemNwUHpNcitrZXJzU1Zx
            MXFxYmF3VHhWVGx4V0hDRVJweGFlcFkKJ+2G0YtjXBKS8vFLimY7Yq20SqxLLIGn
            AzByE3hw+AdYjJrX4wObRwQTbjNy1OBwoV4n9QDVUY6prnMwRfYEKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T16:38:58Z"
    mac: ENC[AES256_GCM,data:Tk58iNAUTNCJwPt/9UfZAhFMrZn3klD7bB1uvM5IoM2AuQSr45znp7qLmaZDWgqf5DwPERrNX9zbGrgbazQfGAwkVHhF1j7ZRjM0wtQXOECY1asb4NSvCDfqsKpV/xoWCYVPcagSSq5OfTsLsLJuwWXsAakYN1jX7WVGfXp3pMQ=,iv:9aY8Isg+K73cNzgoXD1BVrTHJOSSjE9FuDuvxQNdAj4=,tag:kMs6UiTzw/gpxC2FwRa/fg==,type:str]
    pgp: []
    encrypted_regex: ^((?i)(secret($|[^N])|values|data|stringData|username|auth|.*(token|key|private|pass|secret|domain|ssid|webhook).*))$
    version: 3.7.3
