deployments:
  {% if args.environment == 'dev' %}
  - path: ui
  {% endif %}
  - path: echo-headers
  - path: nginx-helm

commonLabels:
  kluctl-example/environment: "{{ args.environment }}"

overrideNamespace: {{ namespaces.services }}
