discriminator: kluctl-examples-simple-{{ target.name }}

targets:
  - name: simple
    args:
      environment: simple
  - name: another
    args:
      environment: another

args:
  - name: environment
