matrix:
  - name: README
    sources:
      - README.md
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .wordlist.txt
      output: build/dictionary/readme.dic
    pipeline:
      - pyspelling.filters.url:
      - pyspelling.filters.html:
          comments: true
          ignores:
          - code
          - pre
