deployment:
  project:
    url: git@github.com:kluctl/kluctl-examples-external-deployments.git
    ref: main
    subDir: simple

targets:
  - name: simple-with-external-repos
    args:
      environment: simple-with-external-repos
