apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-headers-deployment
  labels:
    app: echo-headers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-headers
  template:
    metadata:
      labels:
        app: echo-headers
    spec:
      containers:
        - name: echo-headers
          image: "{{ images.get_image('mendhak/http-https-echo') }}"
          ports:
            - containerPort: 80
